name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container: opencfd/openfoam2112-dev
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build and install
        run: |
          #cd ${{ github.workspace }} && source /openfoam/bash.rc && 
          shopt -s expand_aliases && source /openfoam/bash.rc && 
          ./Allwmake
      - name: Test 1DSedim
        run: |
          shopt -s expand_aliases && source /openfoam/bash.rc && 
          cd tests/1DSedim && ./Allrun &&
	  python test_sedimentation.py && ./Allclean
  checkstyle:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: install vera++
        run: |
          sudo apt-get install vera++
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: pull submodule
        run: |
          git submodule init && git submodule update --remote
      - name: Check style
        run: |
          shopt -s expand_aliases && ./foamStyleCheck/checkStyle
  checkpep8:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Python Style Checker
        uses: andymckay/pycodestyle-action@0.1.3
